### ISSUE TITLE
Preserve old history

### ISSUE THREAD

**Issue by afk11** [transmission-php/transmission-php#1]
Over the years people have forked kleiram/transmission-php and added their own commits. Without the old history, it's really not easy for these people to upgrade.

https://github.com/afk11/transmission-php/commits/kleiram-project-upgrade

I ported the changes back on top of kleiram/transmission-php, with some minor tweaks along the way. 
 - preserve author info until now. we didn't write this ourselves.
 - add old changelog stuff.. even though it's ridiculously legacy stuff..
 - Omitted the examples/queues.php thing - that looks like it was fine the way it was before. 
 - change directory back to lib.. It seems moot, but it causes a lot of pain when porting commits that are about files that never existed in this repo.. IMO this shouldn't be changed at this time

Also, based on previous tags, I think the first tag we should do is 2.0.0 so it continues naturally? People probably want php7 stuff ASAP. 

https://github.com/afk11/transmission-php/commits/kleiram-project-upgrade

@Surfoo could you review and check it captures your changes properly? If so we should push this over master

**Comment by Surfoo** [comment]
I retrieved kleiram/tranmission-php and push force to this master branch. All new changes should be now on develop branch.

**Comment by afk11** [comment]
Aw, I spent a while working on this ;) https://github.com/afk11/transmission-php/commits/kleiram-project-upgrade 

I'll PR any other stuff back in

**Comment by afk11** [comment]
It looks like you have these two directories now, which seems weird

src/Transmission
lib/Transmission

I think you can probably rename src back over Transmission to keep those changes, or force push the above branch over develop

**Comment by afk11** [comment]
Thanks, looks ok now!
