### ISSUE TITLE
Request protocol can't be set

### ISSUE THREAD

**Issue by danielkoster** [transmission-php/transmission-php#14]
My Transmission service is accessed with nginx in front of it as a proxy. I do this so my transmission service isn't directly accessible through the internet. Because I access it over HTTPS, the API call can't be made because there is no way to configure the protcol.

https://github.com/transmission-php/transmission-php/blob/develop/lib/Transmission/Client.php#L115

Here `http://` is hardcoded. Perhaps add this as an extra constructor-parameter to the client, or with a `setProtocol()` method?

EDIT: I can create a pull request if you tell me whether a constructor-parameter, method call, or both would be best.

**Comment by Surfoo** [comment]
Hello,

Thanks for your proposal, both will be great (and a default value to `http`), like others params :)
