### ISSUE TITLE
Lowest supported PHP version

### ISSUE THREAD

**Issue by afk11** [transmission-php/transmission-php#5]
It looks like our dev dependencies are forcing us to use a higher PHP version than our released version.

phpunit ^9.1 uses 7.3 and 7.4
phpunit ^8.1 uses 7.2 - 7.4
composer.json says >= 7.4

If we use `phpunit: ^8.1|^9.1` we can allow PHP7.2 - 7.4

`symfony/property-access` package requires ^7.2.5, and I don't want to change existing dependencies.

So what do you think about lowering to 7.2 in composer.json, and changing phpunit (only used in tests) to `^8.1|^9.1` or something along those lines?

**Comment by Surfoo** [comment]
Travis failed with PHP 7.2: https://travis-ci.org/github/transmission-php/transmission-php/builds/688151624

I don't want to get in over my head for a problem of dependencies, maybe we just can drop PHP 7.2 (EOL: end of the year...)

**Comment by afk11** [comment]
Cool, that should help a lot anyway!
