### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by danielkoster** [transmission-php/transmission-php#9]
Hi! I'm working on a Symfony based project and want to connect to Transmission. I found `kleiram/transmission-php` which doesn't work in frameworks due to https://github.com/kleiram/transmission-php/issues/84, which led me to this repository. I see you have done some great work on this repo. Unfortunately, it seems no one can use it yet because there has not been a release since the fork. Do you have plans to create a release any time soon?

**Comment by Surfoo** [comment]
Hello,

You are right! I forgot to create a release since may. It's done now with the release 2.0. You can test it, and if you find some issue, you can suggest a PR :)

**Comment by danielkoster** [comment]
Awesome! I'll check it out tomorrow. For now I have created https://github.com/transmission-php/transmission-php/pull/11. This should fix the xdebug error I saw phpunit was throwing in CI.

**Comment by danielkoster** [comment]
Seems to work. Thanks again! I'll close this for now.
